# Generated by Django 2.2.1 on 2019-09-12 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('code', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=210, verbose_name='Nombre')),
                ('desc', models.CharField(max_length=255, verbose_name='Descripción')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock')),
                ('stock_min', models.PositiveIntegerField(blank=True, null=True, verbose_name='Stock mínimo')),
                ('stock_max', models.PositiveIntegerField(blank=True, null=True, verbose_name='Stock máximo')),
                ('image', models.ImageField(blank=True, upload_to='products_images', verbose_name='Imagen')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
            ],
            options={
                'verbose_name': 'artículo',
                'verbose_name_plural': 'artículos',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'precio',
                'verbose_name_plural': 'precios',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('abstractarticle_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='articles.AbstractArticle')),
            ],
            options={
                'verbose_name': 'artículo',
                'verbose_name_plural': 'artículos',
                'ordering': ['name'],
                'abstract': False,
            },
            bases=('articles.abstractarticle',),
        ),
        migrations.CreateModel(
            name='ArticleWithoutPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('code', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=210, verbose_name='Nombre')),
                ('desc', models.CharField(max_length=255, verbose_name='Descripción')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock')),
                ('stock_min', models.PositiveIntegerField(blank=True, null=True, verbose_name='Stock mínimo')),
                ('stock_max', models.PositiveIntegerField(blank=True, null=True, verbose_name='Stock máximo')),
                ('image', models.ImageField(blank=True, upload_to='products_images', verbose_name='Imagen')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='articles.Category', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'artículo',
                'verbose_name_plural': 'artículos',
            },
        ),
        migrations.AddField(
            model_name='abstractarticle',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='articles.Category', verbose_name='Categoria'),
        ),
        migrations.CreateModel(
            name='ArticleProxi',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Stocks',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('articles.articlewithoutprice',),
        ),
        migrations.CreateModel(
            name='PriceWithDesc',
            fields=[
                ('price_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='articles.Price')),
                ('desc', models.CharField(max_length=210, verbose_name='Tipo de precio')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.ArticleWithoutPrice')),
            ],
            options={
                'verbose_name': 'precio con descripcion',
                'verbose_name_plural': 'precios con descripcion',
                'ordering': ['desc'],
            },
            bases=('articles.price',),
        ),
    ]
