# Generated by Django 2.2.1 on 2019-09-12 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('desc', models.CharField(max_length=255, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'backup',
                'verbose_name_plural': 'backups',
                'ordering': ['id'],
            },
        ),
    ]
