# Generated by Django 2.2.1 on 2019-09-12 22:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import registration.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, help_text='Enter a avatar image', null=True, upload_to=registration.models.custom_upload_to, verbose_name='Avatar')),
                ('bio', models.TextField(blank=True, help_text='Enter a bio', null=True, verbose_name='Bio')),
                ('link', models.URLField(blank=True, help_text='Enter a personal website', max_length=210, null=True, verbose_name='Website')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'perfil',
                'verbose_name_plural': 'perfiles',
                'ordering': ['user__username'],
            },
        ),
    ]
