# Generated by Django 2.2.1 on 2019-09-12 22:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Overhead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('init_cash', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Caja inicial')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total gastos')),
                ('remaining_cash', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Efectivo restante')),
                ('date_overhead', models.DateField(default=django.utils.timezone.now, unique=True, verbose_name='Fecha')),
            ],
            options={
                'verbose_name': 'gasto del día',
                'verbose_name_plural': 'gastos del día',
                'ordering': ['-date_overhead'],
            },
        ),
        migrations.CreateModel(
            name='ItemOverhead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Valor')),
                ('overhead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overheads.Overhead', verbose_name='Gasto')),
            ],
            options={
                'verbose_name': 'gasto',
                'verbose_name_plural': 'gastos',
                'ordering': ['id'],
            },
        ),
    ]
