# Generated by Django 2.2.1 on 2019-09-13 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(max_length=210, verbose_name='Nombre'),
        ),
    ]
